HRNET:
    MODEL:
      INIT_WEIGHTS: true
      NAME: pose_hrnet
      NUM_JOINTS: 17
      PRETRAINED: '/path_to_your_pretrained_backbone/hrnet_w32-36af842e.pth'
      TARGET_TYPE: gaussian
      IMAGE_SIZE:
      - 288
      - 384
      HEATMAP_SIZE:
      - 72
      - 96
      SIGMA: 3
      EXTRA:
        PRETRAINED_LAYERS:
        - 'conv1'
        - 'bn1'
        - 'conv2'
        - 'bn2'
        - 'layer1'
        - 'transition1'
        - 'stage2'
        - 'transition2'
        - 'stage3'
        - 'transition3'
        - 'stage4'
        FINAL_CONV_KERNEL: 1
        STAGE2:
          NUM_MODULES: 1
          NUM_BRANCHES: 2
          BLOCK: BASIC
          NUM_BLOCKS:
          - 4
          - 4
          NUM_CHANNELS:
          - 32
          - 64
          FUSE_METHOD: SUM
        STAGE3:
          NUM_MODULES: 4
          NUM_BRANCHES: 3
          BLOCK: BASIC
          NUM_BLOCKS:
          - 4
          - 4
          - 4
          NUM_CHANNELS:
          - 32
          - 64
          - 128
          FUSE_METHOD: SUM
        STAGE4:
          NUM_MODULES: 3
          NUM_BRANCHES: 4
          BLOCK: BASIC
          NUM_BLOCKS:
          - 4
          - 4
          - 4
          - 4
          NUM_CHANNELS:
          - 32
          - 64
          - 128
          - 256
          FUSE_METHOD: SUM
  
model:
    use_pretrained: false
    pretrained: ''
    use_backbone: True
    frozen_resnet: False
    frozen_mobilenet: False
    backbone_net_name: 'hrnet'  # or 'meta_arch' or 'mobilenet_v2'

    dataset_name: 'coco'
    keypoints_num: 17
    input_size:
        w: 288
        h: 384
    heatmap_size:
        w: 72
        h: 96

    margin_to_border: 1.25 # >=1

    ## use an extra mask module branch or only add a channel to
    use_mask: false
    mask_num: 0

    backbone:

        frozen_backbone: false #
        search_alpha: True
        search_beta: True
        operators: ["Zero", "skip_connect", "Sep_Conv_3x3", "Atr_Conv_3x3","avg_pool_3x3","max_pool_3x3"]

        reserve_layers_num: 4  # only use first 4 layers
        depth: 12
        size_types: [4,8,16,32]
        hidden_states_num: 1
        factor: 10
        input_nodes_num: 1

    subnetwork_name: "CNF"
    branchnet_W: 128
    branchnet_D: 1

    subnetwork_config:

        dataset_name: 'coco'
        parts_num : 5
        cell_config:
            
            one-shot-search: True
            ##### vector representation
            vector_in_pixel : True
            vector_dim: 8
            convolution_mode: '2D'
            ##### vector representation

            search_alpha: true
            search_beta: true
            operators: ["Zero", "skip_connect","Atr_Conv_3x3", "Sep_Conv_3x3"]  #'conv_3x3'] # "Atr_Conv_3x3"

            depth: 6
            cut_layers_num: 3  # first several layers
            size_types: [4,8,16,32]
            hidden_states_num: 1
            factor: 16
            input_nodes_num: 1
  

# images_root_dir: '/data1/public_dataset/mpii/images/'
# annotation_root_dir: '/data1/public_dataset/mpii/annot/'
# person_detection_results_path: '/data1/public_dataset/mpii/annot/'

images_root_dir: '/data1/public_dataset/coco/images/'
annotation_root_dir: '/data1/public_dataset/coco/annotations/'
person_detection_results_path: '/data1/public_dataset/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'

#COCO_test-dev2017_detections_AP_H_609_person
#COCO_val2017_detections_AP_H_56_person.json
  
train:

    batchsize: 24
    random_seed : 2 # for random search
    arch_search_strategy: sync # 'first_order_gradient','random','None','second_order_gradient'
    arch_search_epoch: 0
    arch_search_weight_optimization_flag: false # this need more consideration
    epoch_begin: 0
    epoch_end: 200

    w_optim_name: 'Adam'
    w_momentum: 0.9
    w_lr_cosine_begin: 0.001
    w_lr_cosine_end : 0.00005
    w_weight_decay: 0.0003

    # FOR MultiStepLR
    scheduler_name: MultiStepLR  #MultiStepLR
    LR_STEP: [90, 120, 150]

    LR_FACTOR: 0.25

    # two values below make the trainset splited by split_for_train/split_for_archvalid
    
    split_for_train: 2
    split_for_archvalid: 1

    arch_optim_name: 'Adam'
    arch_lr: 0.001
    arch_weight_decay: 0.01

    heatmap_peak_sigma_factor: 3 # HRNET::MODEL::SIGMA 

    augmentation: true
    aug_scale: 0.30
    aug_rotation: 45
    aug_flip: true
    aug_occlusion: false
    occlusion_prob: 0.5
    occlusion_size: [25,25]
    occlusion_nums: 3

    # extra NOT USED
    mask_loss_weight: 0.5


test:
    
    dataset_name: 'val' # 'val' or 'test'
    batchsize: 64

    bbox_score_threshold: 0.0
    confidence_threshold: 0.2
    oks_nms_threshold: 0.9

    flip_test: true
    ckpt: ''


